---
functional:
  - Пользователь должен иметь возможность зарегестрироваться и войти на сайт разными способами (электронная почта, другие аккаунты поддерживаемых систем)
  - Пользователь должен иметь возможность настройки своего аккаунта
  - Пользователь должен иметь возможность просмотра своего рейтинга и рейтига других пользователей 
  - Пользователь должен иметь возможность просмотра своих задач на сайте 
  - Пользовтель должен иметь возможность перехода в на другие ресурсы непосредственно с личного кабинета
  - На сайте должна быть возможность выбора языка программирования
  - На сайте должна быть возможность баттла с роботом так и с живым человеком
  - В редакторе кода должна быть возможность сброса кода на один или несколько шагов назад
  - Пользователь должен иметь возможность связи с администрацией сайта
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя 
  - Сайт должен иметь мобильную версию и быть читаемым на мобильном устройстве
  - Сайт должен иметь совместимость с последними версиями браузеров
  - Сайт должен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)

implicit:
  - Сайт должен иметь цвета и оформление соответствующее тематике сайта (сайт по баттлам, значит цвета должны отражать суть баттлов)
  - У сайта должен быть  интуитивно понятный и доступный любому пользователю интерфейс
  - Сайт должен иметь либо выбор языка либо быть доступным на том языке, для клиентов какой страны он создавался
  - У сайта должно быть название на главной странице либо логотип
